### ISSUE TITLE
Create a Node.js Application on Web App Repo?

### ISSUE THREAD

**Issue by quangv** [Azure-Samples/app-service-web-nodejs-get-started#2]
The repo on the [Get Started Node.JS](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-nodejs) page doesn't exist? Is this it?

`git clone https://github.com/Azure-Samples/nodejs-docs-hello-world` - this repo doesn't exist?

**Comment by cephalin** [comment]
Apologize. I just made that repo public. Thanks for reporting.
